### ISSUE TITLE
Feature: User can see a grid of cards.

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/memory-game#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can see a grid with n x n cards (n is an integer). All the cards are faced down initially (hidden state)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user goes to the page link, they are taken to a grid with n x n cards. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the established files
- [x] Create a root `div` that will contain the main component
- [x] Create a card component
- [x] Create an array of card components that will be mapped on an 'n' sized grid
- [x] Style the card components to be uniformed and the cursor to be a 'pointer' when hovered.
- [x] Have the cards dynamically change when user hovers (grow in size or wiggle)
- [x] Style the background of the page. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
