### ISSUE TITLE
Feature: User can click on any card to unveil the image that is underneath it 

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/memory-game#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on any card to unveil the image that is underneath it 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When a user clicks on a card, the card will flip over to reveal an image underneath it. User can flip multiple cards together. When two or more cards are flipped over, they will reset.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a second card component that will contain the card image.
- [x]  Style the second card component to match. Provide different image icons for user 
- [x] Add an event listener that will hide the previous card and reveal the new card underneath
- [x] Check that the event listener is working properly
- [x] Add a condition if two cards are revealed that the cards will then reset to show just the original side
- [x] Check that the cards are flipping correctly
- [x] Add an animation that will make the cards look like they are flipping over. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
