### ISSUE TITLE
Feature: User can match two cards 

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/memory-game#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can match two cards 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user flips two cards, the game will check if the cards have been matched. If they are matched, then they will disappear. If they are not matched, then the cards will flip back over. 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update card component to track the first and second card that are flipped over in a new state. 
- [x] Reset the first and second card after the user has flipped over the 2nd one.
- [x] Check that the game is properly updating and resetting the state. 
- [x] Update card component to check if the two states are matched. If they are, hide the two cards. 
- [x] If the cards are NOT a match, then place the timer in the conditional to flip the cards back over.
- [x] Check that the cards are properly matching and being updated. 
- [x] Add a point system that will keep track of the user's guesses
- [x] Style the point system to be visually appealing.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
