### ISSUE TITLE
Feature: User can start a game

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/memory-game#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can start a game

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a home screen that allows users to choose between different levels of difficulty
- [x] Use React router to change the screens between home and the gameboard
- [x] Adjust game-board component to accommodate for differences in difficulty levels
- [x] Check that game-board generates different amount of shapes depending on selected level
- [x] Include a 'return to home' option after completion of game 
- [x] Adjust the game-board's styling to always be in a grid depending on difficulty selected 
- [x] Check that game looks good in mobile and desktop views.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
